### ISSUE TITLE
The html looks completely different 

### ISSUE THREAD

**Issue by njbowen** [bzhanglab/WebGestaltR#42] opened 2024-04-23 22:22 UTC
**I couldn't verify above as no "link" existed.** 

Description of the result that you previously got in the original version, and the new result that you got.

**The html looks completely different and can't get to the Enrichment Results with the html file.  See attached image of WebGestaltR on the left and WebGestaltR-rust on the right.** 
![WebGestaltR_vs_WebGestaltR-rust](https://github.com/bzhanglab/WebGestaltR/assets/12192014/0bb31e0d-6264-46ba-98cb-94d3e117c9a7)

**Comment by iblacksand** [comment] 2024-04-24 14:52
Thank you for reporting the issue with the HTML and the GitHub template. 

This is most likely caused by an issue on our end where the necessary JavaScript files were not at the right location. This should be fixed, and you can try reloading the HTML file. 

You may need to reset your browser cache with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> (<kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> for Mac).

If this does not solve your issue, please let me know.

**Comment by njbowen** [comment] 2024-04-26 21:50
this version? devtools::install_github("bzhanglab/WebGestaltR")
the cran version was still the non rust version as of a couple of days ago.

**Comment by iblacksand** [comment] 2024-04-29 15:09
That is the right version. You shouldn't have to change anything about the HTML file that you had the issue with in the initial post. If you refresh that HTML file it should load correctly. If that does not fix the error, please let me know.

**Comment by njbowen** [comment] 2024-04-29 16:12
i was trying to reinstall the Rust version in it's own micromamba env on mac os and have this error now: ERROR: dependency 'readr' is not available for package 'WebGestaltR'
* removing '/Users/myusername/micromamba/envs/webgestaltR_rust/lib/R/library/WebGestaltR'

**Comment by iblacksand** [comment] 2024-04-29 16:30
This seems like the `readr` package did not install in your environment. What happens if you install `readr` independently?

```R
install.packages("readr")
```

Also, do you have a Mac ARM chip (M1, M2, etc)? If so, do you have the ARM version of R installed? I am not sure of the underlying code in the `readr` package, but if you have the Intel version of R, but a ARM chip, this could cause an installation issue.

**Comment by iblacksand** [comment] 2024-04-29 16:32
Also the HTML file is generated with the Rust version, which is good news. The cookie notification will only appear in the new Rust-based package.

**Comment by njbowen** [comment] 2024-04-29 17:15
It's a intel iMac and R gets installed automatically in the micromamba env, but I'll check to see if that's an issue. No ARM stuff yet.  These errors are only showing up for R inside of conda/mamba/micromamba envs, so maybe it is a compatibility thing with R and the packages, or something similar as you suggest.   
even with installing just readr, I get the same tzdb, vroom and readr errors:
Warning messages:
1: In install.packages("readr") :
  installation of package 'tzdb' had non-zero exit status
2: In install.packages("readr") :
  installation of package 'vroom' had non-zero exit status
3: In install.packages("readr") :
  installation of package 'readr' had non-zero exit status

last question(s), will the default, CRAN, version eventually change to the rust version? or will there always be the pre-Rust and post-rust options for webgestaltR?  i noticed the name is the same now both versions as WebGestaltR .    also saw the alternate/diff web url beginning with 2024., how will that work?   thanks and all the best, -

**Comment by iblacksand** [comment] 2024-04-29 19:08
It is interesting that `readr` is not installing correctly. The [readr github page](https://readr.tidyverse.org/) suggests installing `tidyverse`, which will install `readr` along with it.

```R
# The easiest way to get readr is to install the whole tidyverse:
install.packages("tidyverse")
```

Perhaps that can fix the installation problem. I am not familiar with `mamba`, but there appears to be a package that you can use from [conda-forge/r-readr-feedstock](https://github.com/conda-forge/r-readr-feedstock).

```shell
conda config --add channels conda-forge
conda config --set channel_priority strict

mamba install r-readr
```

For the last question, we aim to upload the new R Package to CRAN, but it will require some configuration changes on our end, as CRAN has different policies for packages using Rust.

[2024.webgestalt.org](https://2024.webgestalt.org/) is the new version of webgestalt that uses the new Rust package in the backend, along with new features, such as the ability to run analysis with multiple lists at a time. 

The gene set data has also been updated. We are keeping `2024.webgestalt.org` on the separate URL for the time being, as the new data will change the results of the analysis, and we want to give users time to transition to the new version. Over time, 2024.webgestalt.org will become www.webgestalt.org, and the current website will move to 2019.webgestalt.org.

If you want to use the new data, you can add `hostName = "https://2024.webgestalt.org"` as a parameter to the `WebGestaltR` function. I'll add this to the documentation as well.

**Comment by njbowen** [comment] 2024-04-29 19:27
It's a intel iMac and R gets installed automatically in the micromamba env, but I'll check to see if that's an issue. No ARM stuff yet.  These errors are only showing up for R inside of conda/mamba/micromamba envs, so maybe it is a compatibility thing with R and the packages, or something similar as you suggest.   
even with installing just readr, I get the same tzdb, vroom and readr errors:
Warning messages:
1: In install.packages("readr") :
  installation of package 'tzdb' had non-zero exit status
2: In install.packages("readr") :
  installation of package 'vroom' had non-zero exit status
3: In install.packages("readr") :
  installation of package 'readr' had non-zero exit status

last question, will the default, CRAN, version eventually change to the rust version? or will there always be the pre-Rust and post-rust options for webgestaltR?  i noticed the name is the same now both versions as WebGestaltR .    also saw the alternate/diff web url beginning with 2024., too.  thanks and all the best, -

**Closed** 2024-04-29 19:54 UTC
Labels: bug
