### ISSUE TITLE
[www.webgestalt.org] server certificate verification failed

### ISSUE THREAD

**Issue by shengqh** [bzhanglab/WebGestaltR#48] opened 2024-06-18 16:41 UTC
We used WebGestaltR in our routine RNAseq pipeline. Today, it failed with following error. Since it was failed inside of WebGestaltR, I am wondering if there is any issue in server side? Thanks.

```
Error in curl::curl_fetch_memory(url, handle = handle) :
  SSL peer certificate or SSH remote key was not OK: [www.webgestalt.org] server certificate verification failed. 
CAfile: none CRLfile: none
Calls: WebGestaltR ... request_fetch -> request_fetch.write_memory -> <Anonymous>
```

**Comment by shengqh** [comment] 2024-06-18 16:56
After loading WebGestaltR library, add the following line solved the problem:

```{r}
httr::set_config(httr::config(ssl_verifypeer = FALSE))
```

**Comment by iblacksand** [comment] 2024-06-18 17:34
Sorry for the error. This was caused by a certificate chain issue that should be fixed. You should be able to run the command without any additional commands.

**Comment by iblacksand** [comment] 2024-06-18 19:00
If this error reappears, please let us know. I will close this issue for now.

**Closed by iblacksand** 2024-06-18 19:00 UTC
Labels: bug
